### ISSUE TITLE
Próximo evento pesquisa

### ISSUE THREAD

**Issue by victorgso001** [devsertao/pesquisa-guilda#1]
Tema
Carreira de pesquisa: Qual caminho seguir?

Data: 16/10 (sexta-feira) 19:30h

Formato
Mesa de bar (Conversa informal)

Participantes confirmados:
Rodrigo Ramos (UNIVASF)
Ahirton Lopes (FIAP)
Jesse Nery (Egresso UNIVASF, professor IFBA)

Tópicos abordados

Início de carreira como pesquisador;
Pesquisa no setor público e privado;
A pesquisa como trabalho;
Possibilidade de ser pesquisador sem ser professor;
Visão da área no Brasil e no mundo;
Por onde começar na carreira;

Mediador(es):

Daladier Sampaio (@DelmiroDaladier)
Victor Gustavo (@victorgso001)

Participantes:

Ahirton Lopes:
Nordestino até o tutano e muito orgulhoso de ser maranhense. Ahirton Lopes é Cientista de Dados na Magna Sistemas, atuando na Secretaria de Educação do Estado de São Paulo, e professor de MBA na FIAP, bem como fundador e co-organizador na AI Brasil. Apaixonado por psicologia e inovação em geral, possui mestrado em Engenharia Elétrica pela Universidade Presbiteriana Mackenzie (UPM) e é doutorando em Engenharia Elétrica e Computação na mesma instituição.

Rede Social:[LinkedIn](https://linkedin.com/in/ahirton/)
[github](https://github.com/AhirtonLopes)
[Twitter](https://twitter.com/AhirtonLopes/)

Foto: 
![image](https://user-images.githubusercontent.com/34478635/95076308-03bf9a80-06e8-11eb-8e53-f31bcd8e7673.png)

Rodrigo Ramos:
Professor da UNIVASF, é doutor em Engenharia Elétrica pela Universidade Estadual de Campinas (UNICAMP). Atua como pesquisador na área de ciência da computação, nas áreas de análise de sinais eletrofisiológicos, transformadas wavelet aplicadas a sinais digitais, processamento de sinais e imagens médicas.

Rede Social: [LinkedIn](https://www.linkedin.com/in/rodrigo-ramos-2368b830)

Foto: 
![image](https://user-images.githubusercontent.com/34478635/95076480-46817280-06e8-11eb-86fa-74248e553c36.png)

Jesse Nery
Egresso do curso de Engenharia da computação da UNIVASF, é doutorando pelas Universidades de Aveiro e Porto. Professor do IF Baiano do campus de Senhor do Bonfim

Rede Social:[LinkedIn](https://www.linkedin.com/in/jesse-nery-filho-86501049/)

Foto: 
![image](https://user-images.githubusercontent.com/34478635/95076566-6ca71280-06e8-11eb-8338-e058ec65e42f.png)

SCRIPT:
- Apresentação (@Gabrielr2508) -> 19h;
- Conversa -> Após a abertura -> 40 min a 1h;
- Encerramento.

**Comment by victorgso001** [comment]
Já conversei com o professor Rodrigo Ramos, que se dispôs a ajudar e propor nomes para participar. Ainda, participar novamente da conversa

**Comment by gab0gomes** [comment]
E aí, como tá o andamento? Conseguiu falar com Rafael sobre as imagens?

**Comment by victorgso001** [comment]
Ainda não, esses dias tão bem corridos pra mim, mas quero ver se no fim de semana eu fecho um dos convidados pra mesa, tava pensando em convidar o Ahirton Lopes, que é pesquisador na área de IA e tal, palestrante tb, e professor fora daqui, e falei com o professor Rodrigo Ramos, daqui da UNIVASF, que topa participar, mas tem uma semana em específico de outubro que ele não poderia
Tô procurando gente pra ajudar tb a montar

**Comment by victorgso001** [comment]
O Ahirton confirmou que pode participar, só vou fechar a data. Professor Rodrigo já fechou com a data de 16/10. Se tudo se encaixar, fica nessa data mesmo

**Comment by victorgso001** [comment]
Ahirton fechou a data. Então o evento será dia 16/10, se não tiver mais ninguém, com os dois convidados

**Comment by gab0gomes** [comment]
@johnathanALves Adiciona isso nos eventos por favor

**Comment by victorgso001** [comment]
@DelmiroDaladier tá vendo com uns amigos dele pesquisadores da Morotola, mas acho que só mais um tá bom, pra não ficar uma mesa muito grande

**Comment by gab0gomes** [comment]
@victorgso001 já tem o script fechado? participantes, link de rede social, tópicos e etc?

**Comment by victorgso001** [comment]
Os participantes estão definidos, tópicos e script também. Só falta pegar as redes sociais dessa galera, e aquele release pra fazer os banners

**Comment by gab0gomes** [comment]
O que é release? Quando você consegue essas infos?

**Comment by victorgso001** [comment]
Release é aquela informação que a galera dá sobre eles. Posso tentar conseguir o quanto antes. Sei que consigo o de Rodrigo e o de Ahirton, falta só o de Jesse, que @DelmiroDaladier quem tá em contato

**Comment by gab0gomes** [comment]
Pois tenta adiantar isso, já quero agendar a live e começar a divulgar. Me passa pelo menos o nome do pessoal e o script pra adiantar. Entra em contato com @DelmiroDaladier pra ele agilizar tbm!

**Comment by victorgso001** [comment]
Atualizei já a issue, os links eu vou colocando assim que o pessoal mandar

**Comment by gab0gomes** [comment]
Fechando a issue, já que o evento ta planjeado.
